package it.mauriziogusti.interpreteduo;
import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.media.*;import android.os.Bundle;import android.speech.*;import android.speech.tts.*;import androidx.core.content.ContextCompat;import com.getcapacitor.*;import com.getcapacitor.annotation.*;import java.io.*;import java.nio.*;import java.util.*;
@CapacitorPlugin(name="Interpreter",permissions={@Permission(alias="microphone",strings={Manifest.permission.RECORD_AUDIO})})
public class InterpreterPlugin extends Plugin{
 SpeechRecognizer sr;PluginCall speechCall;TextToSpeech tts;boolean ready;AudioTrack track;File wav;String channel;
 @Override public void load(){if(SpeechRecognizer.isRecognitionAvailable(getContext())){sr=SpeechRecognizer.createSpeechRecognizer(getContext());sr.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float v){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onPartialResults(Bundle b){}public void onEvent(int i,Bundle b){}public void onError(int e){if(speechCall!=null){speechCall.reject("SpeechRecognizer error: "+e);speechCall=null;}}public void onResults(Bundle b){ArrayList<String>a=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(speechCall!=null){JSObject o=new JSObject();o.put("text",a!=null&&!a.isEmpty()?a.get(0):"");speechCall.resolve(o);speechCall=null;}}});}tts=new TextToSpeech(getContext(),s->{ready=s==TextToSpeech.SUCCESS;if(ready)tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String s){}public void onError(String s){}public void onDone(String s){getActivity().runOnUiThread(()->play());}});});}
 @PluginMethod public void startListening(PluginCall c){if(ContextCompat.checkSelfPermission(getContext(),Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissionForAlias("microphone",c,"micPermission");return;}listen(c);}
 @PermissionCallback public void micPermission(PluginCall c){if(ContextCompat.checkSelfPermission(getContext(),Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)listen(c);else c.reject("Permesso microfono negato");}
 void listen(PluginCall c){if(sr==null){c.reject("SpeechRecognizer non disponibile");return;}speechCall=c;String l=c.getString("language","it-IT");Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,l);i.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,1);sr.startListening(i);}
 @PluginMethod public void stopListening(PluginCall c){if(sr!=null)sr.stopListening();if(speechCall!=null){speechCall.reject("Ascolto interrotto");speechCall=null;}c.resolve();}
 @PluginMethod public void speak(PluginCall c){String text=c.getString("text","").trim();channel=c.getString("channel","left");if(text.isEmpty()){c.reject("Testo vuoto");return;}if(!ready){c.reject("Sintesi vocale non pronta");return;}String l=c.getString("language","fr-FR");if(!language(l)){c.reject("Lingua TTS non disponibile");return;}stop();wav=new File(getContext().getCacheDir(),"duo-"+UUID.randomUUID()+".wav");Bundle b=new Bundle();String id="u"+UUID.randomUUID();b.putString(TextToSpeech.Engine.KEY_PARAM_UTTERANCE_ID,id);if(tts.synthesizeToFile(text,b,wav,id)==TextToSpeech.SUCCESS)c.resolve();else c.reject("Sintesi vocale fallita");}
 @PluginMethod public void testChannel(PluginCall c){channel=c.getString("channel","left");if(ready&&language("it-IT")){stop();wav=new File(getContext().getCacheDir(),"test-"+UUID.randomUUID()+".wav");Bundle b=new Bundle();String id="t"+UUID.randomUUID();b.putString(TextToSpeech.Engine.KEY_PARAM_UTTERANCE_ID,id);tts.synthesizeToFile(channel.equals("right")?"Test canale destro":"Test canale sinistro",b,wav,id);}c.resolve();}
 boolean language(String l){int r=tts.setLanguage(Locale.forLanguageTag(l));return r!=TextToSpeech.LANG_MISSING_DATA&&r!=TextToSpeech.LANG_NOT_SUPPORTED;}
 @PluginMethod public void stopAudio(PluginCall c){stop();if(tts!=null)tts.stop();c.resolve();}@PluginMethod public void release(PluginCall c){stop();if(sr!=null)sr.destroy();if(tts!=null)tts.shutdown();c.resolve();}
 void play(){if(wav==null||!wav.exists())return;try{byte[]b=read(wav);W d=parse(b);byte[]p=stereo(d.p,d.c,d.bits,"right".equals(channel));int m=AudioTrack.getMinBufferSize(d.rate,AudioFormat.CHANNEL_OUT_STEREO,AudioFormat.ENCODING_PCM_16BIT);track=new AudioTrack.Builder().setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_MEDIA).setContentType(AudioAttributes.CONTENT_TYPE_SPEECH).build()).setAudioFormat(new AudioFormat.Builder().setEncoding(AudioFormat.ENCODING_PCM_16BIT).setSampleRate(d.rate).setChannelMask(AudioFormat.CHANNEL_OUT_STEREO).build()).setBufferSizeInBytes(Math.max(m,p.length)).build();track.play();track.write(p,0,p.length);track.stop();track.release();track=null;}catch(Exception e){stop();}wav.delete();wav=null;}
 static byte[]read(File f)throws IOException{FileInputStream i=new FileInputStream(f);byte[]b=new byte[(int)f.length()];int p=0,n;while(p<b.length&&(n=i.read(b,p,b.length-p))>0)p+=n;i.close();return b;}
 static byte[]stereo(byte[]p,int c,int bits,boolean right)throws IOException{if(bits!=16)throw new IOException("PCM 16 richiesto");int f=p.length/(2*Math.max(1,c));byte[]o=new byte[f*4];for(int i=0;i<f;i++){int q=i*c*2,s=(short)((p[q]&255)|(p[q+1]<<8));if(c>1)s=(s+(short)((p[q+2]&255)|(p[q+3]<<8)))/2;int z=i*4;put(o,z+(right?2:0),s);put(o,z+(right?0:2),0);}return o;}
 static void put(byte[]b,int i,int v){b[i]=(byte)v;b[i+1]=(byte)(v>>8);}
 static W parse(byte[]b)throws IOException{if(b.length<44||b[0]!='R'||b[1]!='I'||b[2]!='F'||b[3]!='F')throw new IOException("WAV invalido");ByteBuffer x=ByteBuffer.wrap(b).order(ByteOrder.LITTLE_ENDIAN);int c=1,r=22050,z=16,a=-1,n=0,p=12;while(p+8<=b.length){String id=new String(b,p,4);int k=x.getInt(p+4);if(id.equals("fmt ")){c=x.getShort(p+10);r=x.getInt(p+12);z=x.getShort(p+22);}if(id.equals("data")){a=p+8;n=Math.min(k,b.length-a);break;}p+=8+k+(k%2);}if(a<0)throw new IOException("data mancante");return new W(r,c,z,Arrays.copyOfRange(b,a,a+n));}
 static class W{int rate,c,bits;byte[]p;W(int r,int c,int b,byte[]p){rate=r;this.c=c;bits=b;this.p=p;}}
 void stop(){if(track!=null){try{track.pause();track.flush();track.release();}catch(Exception e){}track=null;}if(wav!=null){wav.delete();wav=null;}}
 @Override protected void handleOnDestroy(){stop();if(sr!=null)sr.destroy();if(tts!=null)tts.shutdown();super.handleOnDestroy();}
}